#!/usr/bin/with-contenv bash

cd /app/heimdall

mkdir -p /config/uploads
ln -sf /config/env /app/heimdall/.env

if [ ! -f "/config/env" ]; then
	mv /app/heimdall/.env.example /config/env

	SECRET_KEY=$(date +%s | sha256sum | base64 | head -c 32)
	sed -i 's|JWT_SECRET=CHANGE_ME|JWT_SECRET='${SECRET_KEY}'|g' /config/env
	sed -i 's|DB_TYPE=mysql|DB_TYPE=sqlite|g' /config/env
	sed -i 's|DB_STORAGE=$|DB_STORAGE=/config/app.db|g' /config/env
	sed -i 's|UPLOAD_DIR=$|UPLOAD_DIR=/config/uploads|g' /config/env

	npm run db:migrate
	npm run db:seed
fi

# permissions
chown -R abc:abc \
	/config

# chown the app directory, but not node_modules
find /app/heimdall -maxdepth 1 ! -name node_modules ! -name heimdall -exec chown -R abc:abc '{}' \;
