#!/usr/bin/with-contenv bash

cd /app/heimdalljs

mkdir -p /config/uploads

if [ ! -f "/config/env" ]; then
	mv /app/heimdalljs/.env.example /config/env

	SECRET_KEY=$(date +%s | sha256sum | base64 | head -c 32)
	sed -i 's|JWT_SECRET=CHANGE_ME|JWT_SECRET='${SECRET_KEY}'|g' /config/env
	sed -i 's|DB_TYPE=mysql|DB_TYPE=sqlite|g' /config/env
	sed -i 's|DB_STORAGE=$|DB_STORAGE=/config/app.db|g' /config/env
	sed -i 's|UPLOAD_DIR=$|UPLOAD_DIR=/config/uploads|g' /config/env

	npm run db:migrate
	npm run db:seed
fi

ln -sf /config/env /app/heimdalljs/.env

# permissions
chown -R abc:abc \
	/config \
	/app/heimdalljs
